:github-address: https://github.com/hazelcast-guides/kubernetes-external-client
:templates-url: templates:ROOT:page$/
:hazelcast: Hazelcast IMDG
:framework: Kubernetes

= Connect To Hazelcast Running on Kubernetes from Outside

This is a complete example presenting how to use Hazelcast cluster deployed on Kubernetes with Hazelcast Client running outside of Kubernetes.

include::{templates-url}/link-to-repo.adoc[]

== What You’ll Learn

In this guide you will learn how to deploy Hazelcast Kubernetes cluster and connect to it using a client outside Kubernetes.

== Prerequisites

* Up and running https://kubernetes.io/[Kubernetes] cluster (https://minikube.sigs.k8s.io/docs/[Minikube] is good enough)
* Kubernetes command line tool, https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl]

== Configure Hazelcast cluster on Kubernetes

=== Install Hazelcast cluster

There are different ways of deploying Hazelcast to Kubernetes. For the production environment we recommend using Helm.

[tabs]
====

Helm::
+
--
[source, bash]
----
helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
helm repo update
helm install hz-hazelcast --set service.type=LoadBalancer hazelcast/hazelcast
----
--
Kubectl::
+

--
[source, bash]
----
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-kubernetes/master/rbac.yaml

kubectl run hz-hazelcast-0 --image=hazelcast/hazelcast:$HAZELCAST_VERSION -l "role=hazelcast"
kubectl run hz-hazelcast-1 --image=hazelcast/hazelcast:$HAZELCAST_VERSION -l "role=hazelcast"
kubectl run hz-hazelcast-2 --image=hazelcast/hazelcast:$HAZELCAST_VERSION -l "role=hazelcast"

kubectl create service loadbalancer hz-hazelcast --tcp=5701 -o yaml --dry-run=client | kubectl set selector --local -f - "role=hazelcast" -o yaml | kubectl create -f -
----
--

You can check that the Hazelcast cluster is up and running.

[source, bash]
----
kubectl logs hz-hazelcast-0
...
Members {size:3, ver:3} [
        Member [10.216.6.7]:5701 - 6d2100e0-8dcf-4e7c-ab40-8e98e23475e3 this
        Member [10.216.5.6]:5701 - 5ab4d554-fd7d-4929-8475-0ddf79a21076
        Member [10.216.8.6]:5701 - 7f7dd5f4-e732-4575-89d6-a6e823da38da
]
----

At this point you have started a Hazelcast cluster with 3 members. It is exposed with a LoadBalancer service called `hz-hazelcast` and you can check it's external address with the following command.

[source, bash]
----
kubectl get service hz-hazelcast
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)          AGE
hz-hazelcast   LoadBalancer   10.108.141.178   10.96.184.178     5701:31434/TCP   5m44s
----

[NOTE]
====
If you are using Minikube, you need to execute minikube tunnel now in order to get LoadBalancer External IPs assigned.
====

The field `EXERNAL-IP` is the address of your Hazelcast cluster.

[NOTE]
====
At this point you can already start using your Hazelcast cluster externally with the Unisocket Client (`smart-routing: false`), however it means lower performance. To achieve the best performance, use Smart Client as described below.
====

=== Expose each Hazelcast Member

To use Hazelcast Smart Client, every Hazelcast member needs to be accessible with a separate external address. In Kubernetes PODs can be accessed from outside only via services, so the configuration requires creating a separate service (LoadBalancer or NodePort) for each Hazelcast member POD. This can be done manually or using https://metacontroller.app/[Metacontroller] plugin with https://github.com/metacontroller/metacontroller/tree/master/examples/service-per-pod[Service-Per-Pod] Decorator Controller.

[tabs]
====
Manual::
+
--

To create a `loadbalancer` for each running Hazelcast pod you need to run the following command:

[source, shell script]
----
for pod in $(kubectl get pods --selector=role=hazelcast -o jsonpath="{.items[*].metadata.name}"); do \
  kubectl create service loadbalancer ${pod} --tcp=5701 -o yaml --dry-run=client | kubectl set selector --local -f - "name=${pod}" -o yaml | kubectl create -f -; \
done
----
--

Metacontroller::
+
--
- Install Metacontroller plugin

To install https://metacontroller.app/[Metacontroller] plugin, execute the following commands:

[source, shell script]
----
# Create metacontroller namespace.
kubectl create namespace metacontroller
# Create metacontroller service account and role/binding.
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/v1.4.2/manifests/production/metacontroller-rbac.yaml
# Create CRDs for Metacontroller APIs
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/v1.4.2/manifests/production/metacontroller-crds-v1.yaml
# Create Metacontroller StatefulSet.
kubectl apply -f https://raw.githubusercontent.com/metacontroller/metacontroller/v1.4.2/manifests/production/metacontroller.yaml
----

If you have any issues while creating Metacontroller, it may mean that you don't have ClusterRole access to your cluster. Please check https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#defining_permissions_in_a_role[this] for details.

- Install Service-Per-Pod DecoratorController

To install Service-Per-Pod Decorator Controller, you need to execute the following commands.

[source, shell script]
----
kubectl create configmap service-per-pod-hooks -n metacontroller --from-file=hooks
kubectl apply -f service-per-pod.yaml
----

This Decorator Controller automatically creates a service for each POD marked with the following annotations, so you need to add these annotations to your running Hazelcast pods.
[source, yaml]
----
annotations:
    service-per-pod-label: "statefulset.kubernetes.io/pod-name"
    service-per-pod-ports: "5701:5701"
----
--
====

Check the services were created with by running the command:

[source, shell script]
----
$ kubectl get svc
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)          AGE
hz-hazelcast     LoadBalancer   10.108.141.178   10.96.184.178   5701:30915/TCP   11m
hz-hazelcast-0   LoadBalancer   10.175.248.67    35.195.77.97    5701:30915/TCP   11m
hz-hazelcast-1   LoadBalancer   10.175.254.105   104.155.70.30   5701:30440/TCP   11m
hz-hazelcast-2   LoadBalancer   10.175.253.232   34.78.182.50    5701:30305/TCP   11m
----

== Configure Hazelcast Client outside Kubernetes

When we have a working Hazelcast cluster deployed on Kubernetes, we can connect to it with an external Hazelcast Smart Client.

To use Hazelcast client, add Hazelcast client dependency to your application.

[tabs]
====

Java::
+
--
.pom.xml
[source, xml]
----
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast</artifactId>
    <version>${hazelcast.version}</version>
</dependency>
----
--

NodeJS::
+
--
[source, bash]
----
npm install hazelcast-client
----
--
====

Check again the EXTERNAL-IP (or `NODE-IP:NODE_PORT` in case of using NodePort services) of your LoadBalancer service.

[source, bash]
----
kubectl get service hz-hazelcast
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)          AGE
hz-hazelcast   LoadBalancer   10.108.141.178   10.96.184.178     5701:31434/TCP   5m44s
----

Configure the Hazelcast client in your application to connect to the your cluster using `EXTERNAL-IP` (or `NODE-IP:NODE_PORT` in case of using NodePort services).

[tabs]
====

Java::
+
--
[source, java]
----
ClientConfig config = new ClientConfig();
config.getNetworkConfig().addAddress("10.96.184.178");
----
--

NodeJS::
+
--
[source, javascript]
----
const { Client } = require('hazelcast-client');

const clientConfig = {
    network: {
        clusterMembers: [
            'hz-hazelcast'
        ]
    }
};
const client = await Client.newHazelcastClient(clientConfig);
----
--

====

=== Run Hazelcast Client application

You can run the client application with the following command.

[tabs]
====

Java::
+
[source, shell script]
----
mvn -f java/pom.xml package
java -jar java/target/*jar-with-dependencies*.jar
----
--

NodeJS::
+
--
[source, javascript]
----
const { Client } = require('hazelcast-client');

const clientConfig = {
    network: {
        clusterMembers: [
            'hz-hazelcast'
        ]
    }
};
const client = await Client.newHazelcastClient(clientConfig);
----
--

====

Application is a web service that uses Hazelcast Client to connect to the Hazelcast cluster.
To check it works correctly, you can execute the following commands:

[source, shell script]
----
$ curl "localhost:8080/put?key=some-key&value=some-value"
{"response":null}

$ curl "localhost:8080/get?key=some-key"
{"response":"some-value"}
----

You can also check the application logs to see:

[source, shell script]
----
Members [3] {
	Member [10.172.2.8]:5701 - 77fb7da6-79bd-4b5b-9c63-2c425a111c06
	Member [10.172.0.4]:5701 - d63bd9f6-7afd-4b9b-88d3-f3b6afb749f9
	Member [10.172.0.5]:5701 - 049fe137-9cfd-4be8-80a3-d1357a31f6f4
}
----
